name: Sphinx docs to gh-pages

on:
  push:
    # branches:
    #   - main
    tags:
      v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Installing the library
        shell: bash -l {0}
        run: |
          pip install -e .[ci,docs]
          export KFACTORY_DISPLAY_TYPE="image"
          python ./docs/gen_ref_pages.py
          mkdocs gh-deploy
